spring:
  application:
    name : ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pant-nakul/micro-configurations
          clone-on-start: true
server:
  port: 8085

